spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

sms:
  messaging:
    enabled: ${NOTIFICATION_SERVICE_ENABLED:true}
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:}
    api-key: ${NOTIFICATION_API_KEY:}
    sender-id: ${NOTIFICATION_SMS_SENDER_NAME:SHULEHUB}
    provider: ${NOTIFICATION_SMS_PROVIDER:}

logging:
  level:
    tz.co.chambaka.school.management: INFO
    org.springframework.security: WARN
