spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_school_sms}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${MYSQL_USER:sms_user}
    password: ${MYSQL_PASSWORD:Uhambule1972!}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    tz.co.chambaka.school.management: DEBUG
    org.springframework.security: INFO
