package tz.co.chambaka.school.management.model.enums;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    LOGIN,
    LOGIN_FAILED,
    TOKEN_REFRESH,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    REGISTER_SCHOOL,
    REGISTER_TENANT,
    FEE_CREATED,
    FEE_LISTED,
    INVOICE_GENERATED,
    INVOICE_LISTED,
    INVOICE_VIEWED,
    PAYMENT_RECORDED,
    PAYMENT_LISTED,
    PAYMENT_VIEWED,
    BALANCE_VIEWED,
    ACCESS,
    ACCESS_DENIED,
    ERROR
}
