CREATE TABLE audit_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    correction_id VARCHAR(64) NOT NULL,
    scope VARCHAR(20) NOT NULL,
    school_id BIGINT NULL,
    actor_user_id BIGINT NULL,
    actor_email VARCHAR(180),
    actor_role VARCHAR(30),
    action VARCHAR(30) NOT NULL,
    resource_type VARCHAR(80),
    resource_id VARCHAR(80),
    summary VARCHAR(500),
    details TEXT,
    http_method VARCHAR(10),
    http_path VARCHAR(500),
    status_code INT,
    ip_address VARCHAR(80),
    user_agent VARCHAR(500),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    KEY idx_audit_correction (correction_id),
    KEY idx_audit_school_created (school_id, created_at),
    KEY idx_audit_scope_created (scope, created_at),
    KEY idx_audit_actor (actor_user_id),
    KEY idx_audit_action (action),
    CONSTRAINT fk_audit_school FOREIGN KEY (school_id) REFERENCES schools (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
